name: purebapet_app
description: "PetAdopt - Aplicación móvil para adopción de mascotas"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  
  # Supabase
  supabase_flutter: ^2.5.6
  
  # Environment variables
  flutter_dotenv: ^5.1.0
  
  # Image handling
  image_picker: ^1.0.7
  
  # UUID generation
  uuid: ^4.3.3
  
  # Icons
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  # Configurar el archivo .env
  assets:
    - .env